<?php

/**
 * PHP Step Essentials - Input/Output Helper Functions
 * Equivalent to the Go step-essentials/io library
 * 
 * Enhanced for Visual Go workflow engine compatibility.
 * This library handles all input parsing and output formatting,
 * maintaining repository integrity without external file injection.
 */

/**
 * GetInputs parses command line arguments and returns associative array
 * Supports both --inputs YAML and --inputs-file path formats
 * Compatible with Visual Go workflow engine input format
 */
function GetInputs() {
    global $argv;
    
    $inputs = [];
    
    for ($i = 1; $i < count($argv); $i++) {
        if ($argv[$i] === '--inputs' && isset($argv[$i + 1])) {
            // Parse YAML from command line argument
            $yamlContent = $argv[$i + 1];
            // Handle escaped newlines in command line arguments
            $yamlContent = str_replace('\\n', "\n", $yamlContent);
            $inputs = parseWorkflowYaml($yamlContent);
            break;
        } elseif ($argv[$i] === '--inputs-file' && isset($argv[$i + 1])) {
            // Read and parse YAML from file
            $filePath = $argv[$i + 1];
            if (file_exists($filePath)) {
                $yamlContent = file_get_contents($filePath);
                $inputs = parseWorkflowYaml($yamlContent);
            }
            break;
        } elseif (strpos($argv[$i], '--inputs-file=') === 0) {
            // Handle --inputs-file=filename format
            $filePath = substr($argv[$i], strlen('--inputs-file='));
            if (file_exists($filePath)) {
                $yamlContent = file_get_contents($filePath);
                $inputs = parseWorkflowYaml($yamlContent);
            }
            break;
        } elseif (strpos($argv[$i], '--inputs=') === 0) {
            // Handle --inputs=yaml format
            $yamlContent = substr($argv[$i], strlen('--inputs='));
            // Handle escaped newlines in command line arguments
            $yamlContent = str_replace('\\n', "\n", $yamlContent);
            $inputs = parseWorkflowYaml($yamlContent);
            break;
        }
    }
    
    return $inputs;
}

/**
 * SetOutputs formats associative array as YAML and outputs to stdout
 * This output is captured by the workflow engine
 */
function SetOutputs($outputs) {
    echo formatAsYaml($outputs);
}

/**
 * Enhanced YAML parser for workflow engine compatibility
 * Handles the specific YAML format generated by the Visual Go workflow engine
 */
function parseWorkflowYaml($yamlContent) {
    $result = [];
    $lines = explode("\n", trim($yamlContent));
    
    foreach ($lines as $line) {
        $line = trim($line);
        if (empty($line) || strpos($line, '#') === 0) continue;
        
        if (strpos($line, ':') !== false) {
            // Split only on the first colon to handle array values correctly
            $colonPos = strpos($line, ':');
            $key = trim(substr($line, 0, $colonPos));
            $value = trim(substr($line, $colonPos + 1));
            
            // Handle different value types
            if ($value === '') {
                // Empty value
                $result[$key] = '';
            } elseif (preg_match('/^\[(.*?)\]$/', $value, $matches)) {
                // Handle arrays in YAML format [1, 2, 3]
                $arrayStr = $matches[1];
                if (!empty($arrayStr)) {
                    $result[$key] = array_map(function($v) {
                        $v = trim($v);
                        return is_numeric($v) ? (strpos($v, '.') !== false ? floatval($v) : intval($v)) : $v;
                    }, explode(',', $arrayStr));
                } else {
                    $result[$key] = [];
                }
            } elseif (is_numeric($value)) {
                // Handle numeric values
                $result[$key] = strpos($value, '.') !== false ? floatval($value) : intval($value);
            } elseif (in_array(strtolower($value), ['true', 'false'])) {
                // Handle boolean values
                $result[$key] = strtolower($value) === 'true';
            } elseif (preg_match('/^"(.*)"$/', $value, $matches)) {
                // Handle quoted strings
                $result[$key] = $matches[1];
            } else {
                // Handle unquoted strings
                $result[$key] = $value;
            }
        }
    }
    
    return $result;
}

/**
 * Legacy function for backward compatibility
 * @deprecated Use parseWorkflowYaml instead
 */
function parseSimpleYaml($yamlContent) {
    return parseWorkflowYaml($yamlContent);
}

/**
 * Format associative array as YAML output
 * Generates YAML format that the workflow engine can parse
 */
function formatAsYaml($data) {
    $yaml = "";
    
    foreach ($data as $key => $value) {
        if (is_array($value)) {
            // Format arrays as [1, 2, 3]
            $arrayStr = '[' . implode(', ', $value) . ']';
            $yaml .= "$key: $arrayStr\n";
        } elseif (is_bool($value)) {
            $yaml .= "$key: " . ($value ? 'true' : 'false') . "\n";
        } elseif (is_string($value)) {
            // Escape strings that contain special characters
            if (preg_match('/[:\n\r\t]/', $value)) {
                $escaped = addslashes($value);
                $yaml .= "$key: \"$escaped\"\n";
            } else {
                $yaml .= "$key: $value\n";
            }
        } else {
            $yaml .= "$key: $value\n";
        }
    }
    
    return $yaml;
}

?>